### ISSUE TITLE
Can't open barrels

### ISSUE THREAD

**Issue by yunus-cakir** [ellie-semele/expanded-storage#4] opened 2024-01-30 16:02 UTC
Hi! I updated Expanded Storage Fabric 1.20.1 from 10.0.0-beta.3 to the latest supported version but I can't open the barrels even game see the inside.

https://github.com/ellie-semele/expanded-storage/assets/83448525/b054e00e-808b-4757-ae00-e69ac4ee26d2

**Comment by ellie-semele** [comment] 2024-02-02 14:02
Sorry, can't reproduce this myself with Expanded Storage alone, does any kind of error show up in the game logs when interacting with the barrel?

Also if there is a modpack I could easily download to replicate this issue that would be great.

**Comment by yunus-cakir** [comment] 2024-02-03 06:16
> Sorry, can't reproduce this myself with Expanded Storage alone, does any kind of error show up in the game logs when interacting with the barrel?
> 
> Also if there is a modpack I could easily download to replicate this issue that would be great.

Hi again! I was trying to update my custom smp pack that named Valley in modrinth
https://modrinth.com/modpack/valley/version/1.1.7
That's the proper working version. When I update the fabric api and the other mods, Its all fine but expanded storage.

**Comment by ellie-semele** [comment] 2024-02-03 17:00
Thanks for more info, will try to replicate again!

**Comment by ellie-semele** [comment] 2024-02-03 17:37
Just as a note, I'm able to replicate with Valley 1.1.7 with fabric api updated and expanded storage updated only.

```
[17:35:20] [Render thread/ERROR]: Error executing task on Client
java.lang.IllegalStateException: screenSize should never be null...
	at compasses.expandedstorage.impl.client.gui.AbstractScreen.createScreen(AbstractScreen.java:220) ~[expandedstorage-10.1.1-fabric.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.openScreen(ClientNetworking.java:76) ~[fabric-screen-handler-api-v1-1.3+b3afc78b77-b9c3dfa5968b539d.jar:?]
	at net.fabricmc.fabric.impl.screenhandler.client.ClientNetworking.lambda$onInitializeClient$0(ClientNetworking.java:51) ~[fabric-screen-handler-api-v1-1.3+b3afc78b77-b9c3dfa5968b539d.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]```

**Comment by ellie-semele** [comment] 2024-02-03 18:07
Not sure how I managed this one but I broke the config between versions... Pushed a fix to Modrinth: https://modrinth.com/project/F56tBubk/version/QKXAUOit

Sorry for the wait!

**Closed by ellie-semele** 2024-02-03 18:07 UTC
